# Generated by Django 2.0.3 on 2018-03-26 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('year', models.IntegerField(validators=[django.core.validators.RegexValidator(message='4-digits number', regex='^[1-2][0-9][0-9][0-9]$')], verbose_name='Year')),
                ('place', models.CharField(blank=True, max_length=50, verbose_name='Place')),
                ('cultivator', models.CharField(blank=True, max_length=20, verbose_name='Cultivator')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=10, null=True, verbose_name='Value')),
                ('description', models.TimeField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('mtype', models.CharField(choices=[('G', 'Genetic Marker'), ('T', 'Traits')], default='G', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
                ('taxon', models.CharField(blank=True, max_length=50, verbose_name='Taxon')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('population', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultivation_id', to='mm.Cultivation')),
                ('source', models.ManyToManyField(blank=True, related_name='_strain_source_+', to='mm.Strain', verbose_name='pre-generation')),
            ],
        ),
        migrations.AddField(
            model_name='management',
            name='marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marker_id', to='mm.Marker'),
        ),
        migrations.AddField(
            model_name='management',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strain_id', to='mm.Strain'),
        ),
    ]
