# Generated by Django 2.0.3 on 2018-03-27 16:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('mtype', models.CharField(choices=[('g', 'Genetic Marker'), ('p', 'Phenotypic Marker')], default='g', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='MSTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=10, null=True, verbose_name='Value')),
                ('description', models.TimeField(blank=True, verbose_name='Description')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='mm.Marker')),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('year', models.IntegerField(validators=[django.core.validators.RegexValidator(message='4-digits number', regex='^[1-2][0-9][0-9][0-9]$')], verbose_name='Year')),
                ('place', models.CharField(blank=True, max_length=50, verbose_name='Place')),
                ('cultivator', models.CharField(blank=True, max_length=20, verbose_name='Cultivator')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('taxon', models.CharField(blank=True, max_length=50, verbose_name='Taxon')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('population', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strains', to='mm.Population')),
                ('source', models.ManyToManyField(blank=True, related_name='_strain_source_+', to='mm.Strain', verbose_name='pre-generation')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='population',
            unique_together={('name', 'year')},
        ),
        migrations.AddField(
            model_name='mstable',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strains', to='mm.Strain'),
        ),
        migrations.AddField(
            model_name='marker',
            name='population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='mm.Population'),
        ),
        migrations.AlterUniqueTogether(
            name='strain',
            unique_together={('name', 'population')},
        ),
        migrations.AlterUniqueTogether(
            name='mstable',
            unique_together={('strain', 'marker')},
        ),
        migrations.AlterUniqueTogether(
            name='marker',
            unique_together={('name', 'population')},
        ),
    ]
