# Generated by Django 2.0.2 on 2018-03-29 06:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstable',
            name='description',
            field=models.TimeField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='population',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Year number', regex='^[0-9]{0,4}$')], verbose_name='Year'),
        ),
    ]
