# Generated by Django 2.0.2 on 2018-03-29 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0002_auto_20180329_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstable',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
