# Generated by Django 2.0.3 on 2018-03-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mm', '0003_auto_20180329_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='mtype',
            field=models.CharField(choices=[('g', 'Genotype'), ('p', 'Phenotype')], default='g', max_length=20, verbose_name='Type'),
        ),
    ]
